"""The documentation gate covers exports, generated bytes, and runnable examples."""

from __future__ import annotations

import importlib
import inspect
import json
import re
import subprocess
import sys
from copy import deepcopy
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest
from examples.mixing import main as mixing_main
from examples.mixing import run_example
from scripts import generate_docs
from scripts.generate_docs import load_manifest, validate_manifest
from scripts.generate_docs import main as docs_main

import tiergraph.schema
import tiergraph_dot
from tiergraph.machine import MACHINE_VERSION


def test_documentation_gate_is_current() -> None:
    """The in-process gate keeps its validation code inside coverage."""
    assert docs_main(["--check"]) == 0


def test_generated_cli_docs_use_the_accepted_machine_version() -> None:
    """The documented machine header follows the decoder's exported version."""
    rendered = generate_docs.CLI_PATH.read_text(encoding="utf-8")
    header = json.dumps({"machine_version": MACHINE_VERSION}, separators=(",", ":"))
    assert f"`{header}`" in rendered


def test_manifest_shape_errors_are_rejected(tmp_path: Path) -> None:
    """Both the JSON root and the export grouping must be objects."""
    path = tmp_path / "manifest.json"
    path.write_text("[]", encoding="utf-8")
    with pytest.raises(ValueError, match="manifest must be an object"):
        load_manifest(path)
    with pytest.raises(ValueError, match="api_groups must be an object"):
        validate_manifest({"api_groups": []})


def test_entry_fallbacks_cover_undocumented_objects() -> None:
    """Generated entries distinguish aliases from other undocumented values."""

    class Undocumented:
        pass

    Undocumented.__doc__ = None
    module = SimpleNamespace(Path=Undocumented(), singleton=Undocumented())
    assert "type alias" in generate_docs._entry(module, "Path", {})
    assert "singleton" in generate_docs._entry(module, "singleton", {})
    assert generate_docs._signature(object()) == ""


def test_class_entries_include_public_members_once_in_definition_order() -> None:
    """Methods, classmethods, and properties are class reference entries."""

    class Example:
        """Example class."""

        def method(self, value: int) -> int:
            """Return one value."""
            return value

        @classmethod
        def create(cls) -> Example:
            """Create an example."""
            return cls()

        @property
        def ready(self) -> bool:
            """Report readiness."""
            return True

        def _private(self) -> None:
            """Stay out of the public reference."""

    rendered = generate_docs._entry(SimpleNamespace(Example=Example), "Example", {})
    headings = [
        rendered.index("#### `Example.method`"),
        rendered.index("#### `Example.create`"),
        rendered.index("#### `Example.ready`"),
    ]
    assert headings == sorted(headings)
    assert rendered.count("#### `Example.method`") == 1
    assert rendered.count("#### `Example.create`") == 1
    assert rendered.count("#### `Example.ready`") == 1
    assert "Example._private" not in rendered


def test_class_entries_render_static_methods_and_omit_unreadable_members() -> None:
    """CHARACTERIZATION: static methods render; write-only and undocumented members do not."""

    class Example:
        """Example class."""

        @staticmethod
        def helper(value: int) -> int:
            """Return one value."""
            return value

        def undocumented(self) -> None:
            pass

        def _store(self, value: int) -> None:
            """Store a value on the example."""

        write_only = property(None, _store)

    rendered = generate_docs._entry(SimpleNamespace(Example=Example), "Example", {})
    assert "#### `Example.helper`" in rendered
    assert "Static method." in rendered
    assert "Example.undocumented" not in rendered
    assert "Example.write_only" not in rendered


@pytest.mark.parametrize(
    ("stdout", "stderr", "message"),
    [("", "boom", "wrote to stderr"), ("not JSON\n", "", "line 1 is not JSON")],
)
def test_cli_stepping_example_failures_are_rejected(
    monkeypatch: pytest.MonkeyPatch, stdout: str, stderr: str, message: str
) -> None:
    """CHARACTERIZATION: the stepping example must be silent on stderr and JSON on stdout."""
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *args, **kwargs: SimpleNamespace(stdout=stdout, stderr=stderr),
    )
    with pytest.raises(ValueError, match=message):
        generate_docs.cli_bytes()


def test_missing_generated_directive_is_rejected() -> None:
    with pytest.raises(ValueError, match="expected one 'copy-example' directive"):
        generate_docs._replace_directive("plain text", "copy-example", "body")


def test_gate_step_without_a_gloss_is_refused(monkeypatch: pytest.MonkeyPatch) -> None:
    """A step added to `gate` stops the render, naming the step and the fix.

    The contributor-facing gate list takes its order and membership from the
    makefile; only the one-line gloss is written by hand. Adding a step to
    `gate` and forgetting the gloss is therefore the one way to reach this
    render with nothing to say about a step, and the person who did it is
    holding a makefile, not this module.
    """
    monkeypatch.setattr(generate_docs, "gate_steps", lambda: ("lint", "unglossed"))
    with pytest.raises(ValueError, match="gate step 'unglossed' has no gloss"):
        generate_docs.contributing_bytes()


@pytest.mark.parametrize(
    ("stderr", "stdout", "message"),
    [(b"bad", b"", "wrote to stderr"), (b"", b"bad", "output bytes")],
)
def test_mixing_output_failures_are_rejected(
    monkeypatch: pytest.MonkeyPatch, stderr: bytes, stdout: bytes, message: str
) -> None:
    monkeypatch.setattr(
        subprocess,
        "run",
        lambda *args, **kwargs: SimpleNamespace(stderr=stderr, stdout=stdout),
    )
    with pytest.raises(ValueError, match=message):
        generate_docs.mixing_bytes()


def test_cli_failures_are_rejected(monkeypatch: pytest.MonkeyPatch) -> None:
    bad = SimpleNamespace(returncode=1, stderr="bad", stdout="")
    monkeypatch.setattr(subprocess, "run", lambda *a, **k: bad)
    with pytest.raises(ValueError, match="CLI contract failed"):
        generate_docs.check_cli()

    calls = iter(
        [
            SimpleNamespace(returncode=0, stderr="", stdout=""),
            SimpleNamespace(returncode=0, stderr="", stdout=""),
            SimpleNamespace(returncode=0, stderr="", stdout='{"version":"bad"}'),
        ]
    )
    monkeypatch.setattr(subprocess, "run", lambda *a, **k: next(calls))
    with pytest.raises(ValueError, match="version JSON"):
        generate_docs.check_cli()


def test_live_claim_failures_are_rejected(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    page = tmp_path / "claim.md"
    page.write_text("expected", encoding="utf-8")
    monkeypatch.setattr(generate_docs, "ROOT", tmp_path)
    with pytest.raises(ValueError, match="missing or changed"):
        generate_docs.check_live_claims(
            {"live_claims": [{"page": "claim.md", "text": "absent", "name": "x"}]}
        )
    with pytest.raises(ValueError, match="unknown live claim"):
        generate_docs.check_live_claims(
            {"live_claims": [{"page": "claim.md", "text": "expected", "name": "x"}]}
        )


def test_live_claim_predicate_failures(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(tiergraph, "NodeSet", str)
    with pytest.raises(ValueError, match="did not return NodeSet"):
        generate_docs._claim_selection_returns_nodeset()
    monkeypatch.setattr(
        inspect,
        "signature",
        lambda value: SimpleNamespace(return_annotation="bad"),
    )
    with pytest.raises(ValueError, match="execute return annotation"):
        generate_docs._claim_build_results()
    annotations = iter(
        [
            SimpleNamespace(return_annotation="Graph"),
            SimpleNamespace(return_annotation="bad"),
        ]
    )
    monkeypatch.setattr(inspect, "signature", lambda value: next(annotations))
    with pytest.raises(ValueError, match="unroll return annotation"):
        generate_docs._claim_build_results()


def test_python_fence_runtime_and_type_errors(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(generate_docs, "ROOT", tmp_path)
    page = tmp_path / "guide.md"
    page.write_text("```python\nraise RuntimeError('bad')\n```\n", encoding="utf-8")
    with pytest.raises(ValueError, match="RuntimeError: bad"):
        generate_docs.execute_python_fences({page})

    page.write_text(
        "```python\nfrom tiergraph import Graph, dump_bytes\n"
        "serialized: str = dump_bytes(Graph((), (), ()))\n```\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="fence type-check failed"):
        generate_docs.execute_python_fences({page})


def test_python_fence_output_must_match_adjacent_text_fence(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Printed output is exact only when the immediately following fence records it."""
    monkeypatch.setattr(generate_docs, "ROOT", tmp_path)
    page = tmp_path / "guide.md"
    page.write_text(
        "```python\nprint('actual')\n```\n```text\nexpected\n```\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match=r"guide\.md #1: got 'actual\\n'"):
        generate_docs.execute_python_fences({page})

    page.write_text("```python\nprint('unrecorded')\n```\n", encoding="utf-8")
    with pytest.raises(ValueError, match="expected ''"):
        generate_docs.execute_python_fences({page})


def test_page_inventory_and_fence_classification_errors(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    (tmp_path / "docs").mkdir()
    readme = tmp_path / "README.md"
    readme.write_text("```python\npass\n```\n", encoding="utf-8")
    monkeypatch.setattr(generate_docs, "ROOT", tmp_path)
    with pytest.raises(ValueError, match="reader page mismatch"):
        generate_docs.validate_pages(
            {"reader_pages": [], "generated_pages": [], "fences": {}}
        )
    manifest: dict[str, Any] = {
        "reader_pages": ["README.md"],
        "generated_pages": [],
        "fences": {"README.md": []},
    }
    with pytest.raises(ValueError, match="unclassified fence"):
        generate_docs.validate_pages(manifest)


def test_main_wraps_errors_detects_stale_and_writes(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        generate_docs, "load_manifest", lambda: (_ for _ in ()).throw(ValueError("bad"))
    )
    with pytest.raises(SystemExit, match="bad"):
        generate_docs.main(["--check"])

    monkeypatch.setattr(generate_docs, "load_manifest", lambda: {})
    monkeypatch.setattr(generate_docs, "ROOT", tmp_path)
    for name in (
        "validate_manifest",
        "validate_pages",
        "check_live_claims",
        "check_cli",
    ):
        monkeypatch.setattr(generate_docs, name, lambda manifest=None: None)
    target = tmp_path / "nested" / "output.md"
    monkeypatch.setattr(generate_docs, "generated", lambda manifest: {target: b"new"})
    target.parent.mkdir()
    target.write_bytes(b"old")
    with pytest.raises(SystemExit, match="is stale"):
        generate_docs.main(["--check"])
    assert generate_docs.main([]) == 0
    assert target.read_bytes() == b"new"


def test_manifest_mutation_is_rejected() -> None:
    """Removing one export proves that exact API coverage discriminates."""
    manifest = deepcopy(load_manifest())
    removed = manifest["api_groups"]["kernel"].pop()
    with pytest.raises(ValueError, match=rf"missing=.*{removed}"):
        validate_manifest(manifest)


def test_duplicate_manifest_export_is_rejected() -> None:
    """A duplicate fails before set equality can conceal it."""
    manifest = deepcopy(load_manifest())
    manifest["api_groups"]["clock"].append("Graph")
    with pytest.raises(ValueError, match="duplicate tiergraph exports: Graph"):
        validate_manifest(manifest)


def test_companion_export_mutation_is_rejected(monkeypatch: pytest.MonkeyPatch) -> None:
    """A new companion export cannot pass without documentation."""
    monkeypatch.setattr(tiergraph_dot, "__all__", ["dumps", "adversarial_alias"])
    with pytest.raises(ValueError, match="tiergraph_dot export mismatch"):
        validate_manifest(load_manifest())


@pytest.mark.parametrize("module_name", sorted(load_manifest()["secondary"]))
def test_secondary_export_mutation_is_rejected(
    module_name: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Every published secondary surface is held to its module's own `__all__`."""
    module = importlib.import_module(module_name)
    declared = list(getattr(module, "__all__", []))
    monkeypatch.setattr(
        module, "__all__", [*declared, "adversarial_alias"], raising=False
    )
    with pytest.raises(ValueError, match=f"{re.escape(module_name)} export mismatch"):
        validate_manifest(load_manifest())


@pytest.mark.parametrize("module_name", sorted(load_manifest()["secondary"]))
def test_secondary_manifest_omission_is_rejected(module_name: str) -> None:
    """Dropping a declared name from a published list cannot pass unnoticed."""
    manifest = deepcopy(load_manifest())
    removed = manifest["secondary"][module_name].pop()
    with pytest.raises(ValueError, match=f"package=.*{re.escape(removed)}"):
        validate_manifest(manifest)


def test_published_module_without_declared_exports_is_rejected(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A module cannot have a surface published for it that it never declares."""
    monkeypatch.delattr(tiergraph.schema, "__all__", raising=False)
    with pytest.raises(ValueError, match=r"tiergraph\.schema declares no __all__"):
        validate_manifest(load_manifest())


def test_missing_secondary_section_is_rejected() -> None:
    """An absent secondary section would silence the whole surface check."""
    manifest = deepcopy(load_manifest())
    del manifest["secondary"]
    with pytest.raises(ValueError, match="secondary must be an object"):
        validate_manifest(manifest)


def test_mixing_example_subprocess_oracle() -> None:
    """The module runs from a repository checkout and emits the documented bytes."""
    root = Path(__file__).resolve().parent.parent
    result = subprocess.run(
        [sys.executable, "-m", "examples.mixing"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0
    assert result.stderr == ""
    assert result.stdout == json.dumps(run_example(), sort_keys=True) + "\n"


def test_mixing_main_prints_its_result(capsys: pytest.CaptureFixture[str]) -> None:
    """The callable entry point emits the same JSON value and succeeds."""
    assert mixing_main() == 0
    assert json.loads(capsys.readouterr().out) == run_example()


def test_console_script_contract() -> None:
    """The installed console script exposes help and structural version JSON."""
    executable = Path(sys.executable).with_name("tiergraph")
    help_result = subprocess.run(
        [executable], capture_output=True, text=True, check=False
    )
    assert help_result.returncode == 0
    assert help_result.stderr == ""
    assert help_result.stdout.startswith("usage: tiergraph")
    version = subprocess.run(
        [executable, "--version"], capture_output=True, text=True, check=False
    )
    assert version.returncode == 0
    assert version.stderr == ""
    assert set(json.loads(version.stdout)) == {"version"}


@pytest.mark.parametrize("document", ["README.md", "docs/format.md"])
def test_format_version_statement_is_present(document: str) -> None:
    """PROSE GUARD: the published statement of the format version policy stands.

    The refusal behavior and the statement are one deliverable: deleting the
    statement is the one way to undo the policy without changing any code.
    """
    root = Path(__file__).resolve().parent.parent
    prose = " ".join((root / document).read_text(encoding="utf-8").split())
    assert "## Format versions" in (root / document).read_text(encoding="utf-8")
    assert (
        "A tiergraph document declares the format version it was written in. A "
        "reader accepts documents of the version it implements and refuses any "
        "other, naming the version it found and the one it expected."
    ) in prose
    assert (
        "Documents are versioned interchange: they move data between tools that "
        "agree on a version. They are not an archival format, and reading a "
        "document written by a later release is not supported."
    ) in prose
